server:
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 81

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
